name: Build d3d12.dll

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build Release DLL
      run: cargo build --release

    - name: Rename to d3d12.dll
      run: |
        mkdir output
        copy target\release\d3d12_hook.dll output\d3d12.dll

    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: d3d12.dll
        path: output/d3d12.dll
