name: Release DLL

on:
  push:
    branches:
      - main  # или 'master' если у тебя другой
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
  workflow_dispatch: # запуск вручную

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: 🔻 Клонирование репозитория
        uses: actions/checkout@v4

      - name: 🛠️ Установка Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: 🔨 Сборка DLL
        run: cargo build --release

      - name: 📦 Создание релиза
        uses: softprops/action-gh-release@v1
        with:
          tag_name: pre-release
          name: "Pre-Release"
          prerelease: true
          files: |
            target/release/d3d12_hook.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
