name: Build & Release Pre-release DLL

on:
  push:
    branches: [ main ] # или твоя ветка

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 🔽 Checkout кода
      uses: actions/checkout@v4

    - name: 🧰 Установка Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: 🧱 Сборка проекта
      run: cargo build --release

    - name: 📁 Найти DLL
      id: find_dll
      shell: pwsh
      run: |
        $dll = Get-ChildItem -Path target/release -Filter *.dll | Select-Object -First 1
        echo "dll_path=$($dll.FullName)" >> $env:GITHUB_ENV

    - name: 🚀 Создание или обновление pre-release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: pre-release
        name: "Auto Pre-release Build"
        prerelease: true
        files: ${{ env.dll_path }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
